site_name: Awesome Data Philippines
site_description: A catalog of datasets and data sources fof the Philippines
site_author: BNHR
site_url: https://awesomedataphilippines.bnhr.xyz
repo_url: https://github.com/benhur07b/awesomedataphilippines
copyright: Copyright &copy; 2025 BNHR

theme:
  logo: https://raw.githubusercontent.com/benhur07b/stuff/refs/heads/main/bnhr/bnhr-2024-fordarkbg-main.png
  favicon: https://raw.githubusercontent.com/benhur07b/stuff/refs/heads/main/bnhr/favicon.ico
  name: material
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
  font: 
    text:  Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono

extra: 
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/bnhr.xyz
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@bnhrdotxyz
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/bnhrdotxyz
    - icon: fontawesome/brands/github
      link: https://github.com/benhur07b
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/benhur07b


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - static/css/extra.css

plugins:
  - search
  - privacy

nav:
  - About:
    - index.md
  - How-to:
    - how-to/index.md
  - Catalog:
    - catalog/index.md
    - Transport:
      - catalog/transport/index.md
      - Safe Travel PH: catalog/transport/safe-travel-ph.md
      - Mobility Database: catalog/transport/mobility-database.md
      - Transitland: catalog/transport/transitland.md
    - Demography:
      - catalog/demography/index.md
      - Philippine Population Data Archive (PopArchive): catalog/demography/pop-archive.md
    - Governance:
      - catalog/gov/index.md
      - Cities and Municipalities Competitiveness Index (CMCI) Rankings Portal: catalog/gov/cmci.md
      - Philippine Standard Geographic Code: catalog/gov/psgc.md
      - Philippine Local Government Interactive Dataset: catalog/gov/ph-lgu-interactive-dataset.md
    - Environment:
      - catalog/environment/index.md
      - Berkeley Earth Climate Data: catalog/environment/berkeley-earth-climate-data.md
      - Light Pollution Map: catalog/environment/light-pollution-map.md
      - Compendium of Philippine Environment Statistics (CPES): catalog/environment/cpes.md
      - Earthdata Search: catalog/environment/earthdata-search.md
    - Administrative and Infrastructure:
      - catalog/admin-infra/index.md
      - World Administrative Boundaries - Countries and Territories: catalog/admin-infra/world-admininstrative-boundaries.md
      - GADM data (version 4.1): catalog/admin-infra/gadm-v4.1.md
      - Philippines - Subnational Administrative Boundaries: catalog/admin-infra/PH-subnational-admin.md
      - Philippines Roads (OpenStreetMap Export): catalog/admin-infra/PH-roads-osm-export.md
    - Biophysical Data:
      - catalog/bio/index.md
      - Allen Coral Atlas: catalog/bio/allen-coral-atlas.md
      - Project SARAi Interactive Maps: catalog/bio/ph-sarai.md
      - Global Biodiversity Information Facility (GBIF): catalog/bio/gbif.md
    - Health:
      - catalog/health/index.md
      - International Genome Sample Resource (IGSR): catalog/health/igsr.md
    - Climate: 
      - catalog/climate/index.md
      - PHIVOLCS Geomatics Service Request: catalog/climate/PHIVOLCS-gsr.md
